const outcomes = {
	critico: {
		cortante: [
			'Con una precisión mortal, tu hoja corta a través de la armadura del enemigo, dejando una herida sangrante que causa 1d4 PG de daño adicional durante sus próximos 2 turnos.',
			'Con un corte rápido y profundo, desarmas a tu oponente. Su arma cae a 10 pies de él en dirección contrario a tu golpe.',
			'Tu espada corta un tendón crucial, generandole al objetivo desventaja en sus tiradas de ataque con armas durante 1d4 turnos.',
			'Con un movimiento ágil, produces un corte en el rostro del enemigo, dejándolo parcialmente cegado y otorgándole desventaja en su próxima tirada de ataque.',
			'Tu hoja se desliza a través de un punto vital, otorgándote un ataque extra por la adrenalina del momento.',
			'Tu ataque cortante deja una herida tan profunda que el enemigo cae al suelo, quedando derribado durante 1d4 turnos.',
			'Un corte preciso deja el escudo del enemigo inutilizable, reduciendo su bonificador de CA durante 1d4 turnos.',
			'Con un giro sorpresa, cortas la bolsa de componentes mágicos del enemigo, impidiéndole lanzar conjuros que requieran componentes materiales durante 1d4 turnos.',
			'Un corte en la pierna hace que tu oponente cojee, generando ventaja en ataques de oportunidad contra él durante 1d4 turnos.',
			'Tu arma se desliza con tanta precisión que puedes elegir a qué parte del cuerpo apuntar, dando lugar a un daño crítico adicional de 1d8 PG.',
			'Tu hoja se mueve con una rapidez asombrosa, causando 1d8 PG de daño adicional por el corte profundo.',
			'Con un tajo, abres la defensa del enemigo, permitiendo a un aliado cercano realizar un ataque de oportunidad.',
			'El filo de tu arma causa una herida que dificulta la concentración del enemigo, imponiéndole desventaja en sus tiradas de conjuro durante 1d4 turnos.',
			'Tu corte apunta a las articulaciones del enemigo, restringiendo su movimiento y reduciendo su velocidad en 10 pies durante 1d4 turnos.',
			'El enemigo queda marcado por tu ataque, otorgando ventaja a cualquier ataque contra él durante 1 turno.',
			'Tu hoja desliza tan suavemente que causas un daño crítico adicional de 1d8 PG sin alertar a otros enemigos cercanos.',
			'Con un corte audaz, dañas parte del equipo del enemigo, reduciendo su bonificador de CA hasta terminar el combate.',
			'Tu ataque deja un corte tan impresionante que las criaturas enemigas a menos de 20 pies deben realizar una tirada de salvación de sabiduría CD 14 o quedarán asustados hasta el fin de tu siguiente turno.',
			'Con un golpe maestro, debilitas el agarre del enemigo, obligándolo a soltar cualquier objeto que sostenga.',
			'Tu corte es tan preciso que reduce el tiempo de recuperación del enemigo, añadiendo 1 turno extra a cualquier efecto negativo que tenga.',
			'El enemigo queda conmocionado por la ferocidad de tu ataque, quedando aturdido hasta el fin de su siguiente turno.',
			'El sonido desgarrador de tu corte resuena en el aire, distrayendo a los enemigos a menos de 10 pies, otorgando ventaja a los ataques de tus aliados contra ellos durante 1 turno.',
			'Tu ataque hiere profundamente la mano de tu enemigo, reduciendo el daño de ataque con armas en 1d4 durante sus siguientes 1d4 turnos.',
			'Con un movimiento elegante, te posicionas detrás del enemigo después de tu ataque, dándote un ataque extra.',
			'El corte inflige dolor insoportable, haciendo que el enemigo quede aturdido hasta el final de su siguiente turno.',
			'Tu hoja corta tan velozmente al objetivo que salpica de sangre a los enemigos que se encuentren a 10 pies o menos. Deben realizar una tirada de salvación de sabiduría CD 14 o quedar asustados hasta el final de su siguiente turno.',
			'Con un movimiento refinado, tu ataque no solo daña sino que también hasta retroceder al enemigo 5 pies en la dirección que elijas.',
		],
		perforante: [
			'Tu puntería es perfecta, y logras atravesar un punto vital del enemigo, causándole 1d8 PG de daño adicional.',
			'Con una estocada veloz, inmovilizas temporalmente la extremidad de tu oponente, otorgándote ventaja en tu próximo ataque.',
			'Tu arma se hunde profundamente en el cuerpo del enemigo, causándole una hemorragia que le produce 1d6 PG de daño extra en cada turno hasta tratar la herida.',
			'Con precisión quirúrgica, logras perforar el morral de tu enemigo, dejando caer sus pertenencias e impidiéndole lanzar conjuros que requieran componentes materiales hasta el final del combate.',
			'El impacto perforante deja a tu oponente sin aliento, reduciendo a la mitad su movimiento durante 1d4 turnos.',
			'Con gran habilidad y potencia logras atravesar y dañar la armadura del enemigo, reduciendo su bonificador de CA hasta finalizar el combate.',
			'Tu proyectil encuentra su camino a los ojos del enemigo, dejándolo cegado durante 1d4 turnos.',
			'Con un impulso feroz, tu arma deja al enemigo en un estado vulnerable, todos los ataques contra él tienen ventaja hasta el final de su siguiente turno.',
			'Tu ataque acierta tan precisamente que incapacitas una de las extremidades del enemigo, dándole desventaja en su próximo ataque.',
			'El golpe es tan potente que el enemigo queda aturdido, hasta el final de su próximo turno.',
			'Con una puntería excepcional, atraviesas una articulación del enemigo, reduciendo su velocidad a la mitad hasta tratar la herida.',
			'La fuerza de tu ataque, además del daño, empuja al enemigo 5 pies en dirección contraria a tí.',
			'Aprovechas un punto débil en la armadura del enemigo, causando un daño adicional de 1d8 PG.',
			'El impacto de tu ataque deja al enemigo sangrando, causándole un daño continuo de 1d4 durante 3 turnos.',
			'Golpeas con tal precisión que desactivas temporalmente una extremidad del enemigo (a tu elección), impidiéndole usarla durante 1 turno.',
			'Con un golpe bien colocado, desconcentras al enemigo, otorgándole desventaja en su próxima tirada de ataque.',
			'El impacto de tu golpe desorienta a tu enemigo, causando que caiga tumbado al suelo.',
			'Atraviesas un punto vital de tu enemigo, causando que quede debilitado y sufra una reducción de 1d4 en cada una de sus tiradas de daño durante sus siguientes 2 turnos.',
			'Tu golpe es tan poderoso que desequilibra y deja expuesto al enemigo, causando que cualquier ataque en su contra obtenga un bonificador de 1d4 en las tiradas de daño hasta el comienzo de su siguiente turno.',
			'Con un ángulo preciso, tu ataque genera el mismo daño a otro enemigo que se encuentre a 5 pies del objetivo.',
			'La herida abierta por tu ataque emite un sonido aterrador. Los enemigos que puedan verlo deben realizar una tirada de salvación de sabiduría (CD 14) o quedar asustados hasta el final de su siguiente turno.',
			'Tu arma se entierra en el objetivo de forma brutal. Los enemigos que puedan verlo retroceden 5 pies en dirección contraria a tí.',
			'Tu ataque revela una debilidad en el enemigo, otorgando ventaja a tus aliados en sus próximos ataques contra él hasta su siguiente turno.',
			'La increíble precisión de tu golpe te motiva, permitiéndote un ataque adicional inmediato contra el mismo enemigo.',
			'Tu impacto es tan potente que rompe instantáneamente la concentración de tu enemigo.',
			'La potencia de tu ataque hace que el enemigo suelte un objeto o arma que estuviera sosteniendo.',
		],
		contundente: [
			'Con un golpe poderoso, aturdes a tu enemigo, dejándolo incapacitado durante 1d4 turnos.',
			'Tu arma se estrella contra la armadura del enemigo dañandola temporalmente, reduciendo su bonificador de CA durante 1d4 turnos.',
			'El impacto es tan fuerte que tu oponente queda derribado.',
			'Con una fuerza tremenda, causas una conmoción cerebral temporal a tu enemigo, dándole desventaja en todas sus acciones durante 1d4 turnos.',
			'El sonido del impacto resuena por el campo de batalla, intimidando a otros enemigos cercanos imponiéndoles desventaja en sus siguientes tiradas de ataque.',
			'Con un golpe en el punto correcto, golpeas el arma del enemigo dejándolo desarmado.',
			'El poder de tu golpe empuja al enemigo 10 pies hacia atrás.',
			'Tu golpe contundente deja un moretón masivo, causando 1d6 PG de daño adicional por el trauma interno.',
			'La fuerza de tu ataque deja al enemigo sin respiración, reduciendo a la mitad su movimiento durante 1d4 turnos.',
			'Con un movimiento rápido, golpeas las piernas del enemigo, dejándolo paralizado hasta el final de su siguiente turno.',
			'El impacto de tu golpe es tan fuerte que genera que el objetivo choque y desestabilice a otro enemigo que se encuentre a 5 pies. Ambos deben realizar TS de Destreza (CD 13) para no quedar tumbados',
			'Tu golpe es tan fuerte que rompe automáticamente la concentración del enemigo, finalizando cualquier conjuro en el que estuviese concentrado.',
			'El enemigo es lanzado al aire por la fuerza de tu golpe, cayendo a 10 pies en dirección del golpe y quedando aturdido hasta el final de su siguiente turno.',
			'El impacto resonante distrae a los enemigos cercanos, dándoles desventaja en sus tiradas de ataque durante 1 turno.',
			'La potencia de tu ataque interrumpe la reacción y cualquier acción que el enemigo estuviera preparando.',
			'La energía de tu ataque te motiva, otorgándote un bonificador de 1d4 en tu próxima tirada de ataque.',
			'El impacto de tu arma genera esquirlas que ciegan temporalmente al enemigo hasta el final de su siguiente turno.',
			'Con un movimiento perfecto, golpeas y desplazas al enemigo en cualquier dirección que elijas, sin que pueda resistirse.',
			'Tu golpe es tan potente que infunde temor en el objetivo. Este queda asustado por tí hasta pase un turno sin que lo golpees.',
			'Con un giro rápido, usas tu arma para desequilibrar al enemigo, dejándolo de rodillas y otorgándote un ataque adicional.',
			'El enemigo queda temporalmente desorientado, desentendiéndose de cualquier plan o táctica que estuviera usando.',
			'El sonido de tu golpe asusta a otros enemigos, haciendo que los que estén a 30 pies o menos de tí retrocedan 5 pies.',
		],
	},
	pifia: {
		cortante: [
			'Al intentar atacar, tu espada se engancha en tu equipo, dejándote expuesto y otorgando ventaja a los ataques contra tí hasta el comienzo de tu próximo turno.',
			'Mientras balanceas tu arma, resbalas, quedándote tumbado en el suelo.',
			'Tu ataque es tan descontrolado que accidentalmente dañas a un aliado que se encuentre dentro del alcance.',
			'Tu arma se queda atascada en una pared o árbol, dejándote sin ella hasta que gastes una acción para recuperarla.',
			'Intentas un corte poderoso, pero terminas girando en círculo, desorientándote y otorgando ventaja en todos los ataques contra tí hasta el comienzo de tu próximo turno.',
			'Tu hoja choca contra el suelo, causando chispas que te ciegan temporalmente hasta el final de tu próximo turno.',
			'En un intento de maniobra acrobática te desequilibras, fallando tu ataque y perdiendo el resto del turno.',
			'Tu ataque falla tan estrepitosamente que los enemigos a 5 pies tiene la oportunidad de realizar un ataque de oportunidad contra ti.',
			'Al intentar atacar, tu arma se te va de las manos de las manos, fallando tu ataque y tu arma cayendo a 10 pies de tí en dirección de tu ataque.',
			'En un ataque increíblemente desprolijo, te golpeas a ti mismo.',
			'El balanceo de tu hoja es tan amplio que quedas desprotegido, todos los ataques enemigos contra ti tienen ventaja hasta el comienzo de tu próximo turno.',
			'El peso de tu arma te arrastra, dejándote fuera de posición y alejándote 5 pies de tu objetivo.',
			'En un intento por atacar, el filo de tu arma choca contra una superficie sólida, mellándola y reduciendo su daño en 1d4 hasta que puedas dedicar un descanso corto reparándola.',
			'Al mover tu arma, accidentalmente cortas la tira de tu morral, cayendo al suelo y exponiendo su contenido.',
			'El ataque es tan desviado y desprolijo que quedas expuesto mortalmente ante el enemigo, si un enemigo te golpea antes del comienzo de tu siguiente turno será automáticamente un crítico.',
			'El impulso de tu ataque te lleva a chocar con un objeto o criatura cercana, quedando aturdido hasta el comienzo de tu siguiente turno.',
			'Tu arma se engancha en la ropa o armadura del enemigo, dejándote desarmado hasta que gastes una acción adicional desenredándola.',
			'El filo de tu arma choca contra una armadura o escudo, generando chispas que te ciegan temporalmente hasta el comienzo de tu siguiente turno.',
			'Al intentar una maniobra compleja, te enredas con tu propia arma, fallando el ataque y perdiendo el resto del turno.',
			'Tu arma choca contra la armadura del enemigo de manera tal que produce un fuerte sonido, alertando a enemigos que se encuentren a 150 pies o menos.',
			'El fallo es tan notorio que cualquier enemigo que lo vea se siente motivado, otorgándoles ventaja en su siguiente tirada de ataque (contra tí o un aliado).',
			'Al fallar el ataque, consumes demasiada energía, otorgándote desventaja en tu próxima tirada de ataque.',
			'El peso de tu arma te desequilibra, dándole tus enemigos cercanos oportunidad clara de alejarse inmediatament 5 pies sin provocar ataques de oportunidad.',
			'Tu arma choca contra fuertemente contra defensa del enemigo, enviando vibraciones dolorosas a través de tu brazo, dandote desventaja en tu sigueinte tirada de ataque.',
			'Al fallar el ataque, cortas accidentalmente tu bolsa de componentes mágicos, no pudiendo realizar conjuros que requieran componente material hasta gastar una acción recogiendolos.',
			'El fallo de tu ataque es tan desmoralizante que pierdes momentáneamente la confianza. Tienes desventaja en tu siguiente tirada de ataque.',
		],
		perforante: [
			'Tu ataque falla estrepitosamente, y en el proceso, dejas expuesta una parte vital, otorgando ventaja al siguiente ataque enemigo contra ti.',
			'Tu proyectil se desvía peligrosamente, impactando contra el aliado más cercano a tu objetivo.',
			'Tu intento de atravesar al enemigo es tan descontrolado que te desequilibras, otorgando un ataque de oportunidad al enemigo.',
			'El arma se atasca y debes gastar 1 acción recuperándola.',
			'Fallas de manera tan ridícula, que los enemigos que puedan verlo se encuentran motivados. Obtienen ventaja en su siguiente tirada de ataque.',
			'Al intentar un ataque, tu arma se desliza de tus manos y termina a 10 pies de distancia en una dirección aleatoria.',
			'Un fallo en tu técnica te desequilibra, haciendo que caigas al suelo tumbado.',
			'Tu ataque es tan predecible que el enemigo fácilmente lo esquiva y se burla, reduciendo tu moral y dandote desventaja en tu próximo ataque.',
			'Al intentar un ataque rápido, pierdes el agarre de tu arma y esta cae a tus pies.',
			'Tu ataque fallido te deja expuesto, otorgando un ataque de oportunidad al enemigo.',
			'Tu arma se enreda en tu equipo o morral, haciendote perder el resto del turno y tu reacción.',
			'La inercia del fallo te deja temporalmente desorientado, haciendote perder el resto del turno y tu reacción.',
			'Dañas torpemente tu arma, reduciendo su daño en 1d4 hasta finalizar el combate.',
			'Fallas estrepitosamente y te desmoralizas, perdiendo cualquier bonificación de ataque que tengas durante 1d4 turnos.',
			'Tu golpe es tan desviado que dañas una de tus piernas, reduciendo tu velocidad de movimiento a la mitad durante 1d4 turnos.',
			'Tu intento fallido de golpear desvía tu atención, otorgando ventaja en la próxima tirada de ataque a los enemigos que se encuentren a 5 pies de tí.',
			'Al fallar, tu arma se atasca en el equipo o armadura del enemigo, permitiéndole realizar un ataque de oportunidad contra ti.',
			'El fallo de tu ataque te agota, haciendo que pierdas el resto del turno y tu reacción.',
			'La inercia del movimiento hace que accidentalmente dañes tu tu morral, dejando caer tus objetos. No puedes realizar conjuros que requieran componente material hasta gastar una acción juntando tus materiales',
		],
		contundente: [
			'En tu intento por golpear, pierdes el equilibrio y quedas expuesto, otorgando ventaja en el próximo ataque enemigo contra ti.',
			'El golpe es tan descontrolado que rebota y te golpeas a ti mismo.',
			'Al balancear tu arma, calculas mal y golpeas a un aliado que se encuentre dentro del alcance.',
			'El arma se escapa de tus manos y queda a 15 pies de distancia en una dirección aleatoria.',
			'Tu arma choca contra una superficie dura, enviando vibraciones dolorosas a través de tu brazo y otorgándote desventaja en tu próximo ataque.',
			'Te esfuerzas demasiado en el golpe, quedando agotado y perdiendo tu movimiento hasta tu siguiente turno.',
			'Un movimiento erróneo tira de un músculo, dándote desventaja en todos los ataques durante 1d4 turnos.',
			'El enemigo esquiva tu ataque fácilmente y se burla, reduciendo tu moral y causando que tu próximo ataque tenga desventaja y el suyo ventaja.',
			'En un intento de realizar un golpe poderoso, tu arma se queda atascada en el suelo, y debes gastar una acción para recuperar su control.',
			'El retroceso de tu ataque contundente te hace perder el equilibrio, dando ataque de oportunidad a los enemigos que se encuentren a 5 pies.',
			'Tu arma golpea el suelo con tanta fuerza que rebota y te golpea, causándote daño y dejandote aturdido hasta el final de tu siguiente turno.',
			'La inercia del movimiento hace que te deslices, moviéndote 5 pies en una dirección no deseada.',
			'El golpe errado te deja desorientado, otorgando ventaja a todos los ataques enemigos contra tí durante 1 turno.',
			'La potencia de tu golpe errado te hace girar, dejándote de espaldas al enemigo y dándole un ataque de oportunidad.',
			'El retroceso de tu ataque afecta temporalmente tus articulaciones, reduciendo tu bonificador de daño en 1d4 durante los siguientes 2 turnos.',
			'El fallo es tan ridículo que reduces la moral de tus aliados que puedan verlo, otorgándoles desventaja en sus próximas tiradas de ataque.',
			'Tu arma queda mal agarrada, finalizando tu ataque e impidiéndote realizar un segundo ataque en tu próximo turno.',
			'El fallo te deja temporalmente exhausto, reduciendo tu velocidad de movimiento a la mitad durante 1d4 turno.',
			'Tu arma se enreda en tu equipo o morral, haciendote perder el resto del turno y tu reacción.'
		],
	},
};

export default outcomes;
